-- :help options
vim.opt.backup = false                              -- Don't make backup of the file
vim.opt.clipboard = "unnamedplus"                   -- Enable copy/paste clipboard
vim.opt.cmdheight = 2               
vim.opt.completeopt = {"menu", "menuone", "noselect" }
vim.opt.conceallevel = 0
vim.opt.fileencoding = "utf-8"
vim.opt.hlsearch = false
vim.opt.ignorecase = true
vim.opt.mouse = "a"
vim.opt.pumheight = 10
--vim.opt.showtabline = 2
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.splitbelow = true
vim.opt.termguicolors = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.scrolloff = 8
vim.opt.relativenumber = false
vim.opt.nu = true
vim.opt.expandtab = true
vim.opt.hidden = true
vim.opt.showmode = false
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.numberwidth = 4
vim.opt.cursorline = false
vim.opt.errorbells = true
vim.opt.wrap = false
vim.opt.signcolumn = "yes"
