[theme]
theme = "srcery"
[icons]
icons = "awesome6"

[[block]]
block = "disk_space"

[[block]]
block = "memory"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "$icon $1m.eng(w:4)"

[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 5

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime()"

[[block]]
block = "battery"

[[block]]
block = "net"
format = "^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) $ssid"
