theme = "nord-dark"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 5
format = "{volume}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}{time}"

[[block]]
block = "networkmanager"
on_click = "nm-connection-editor" 
ap_format = "{ssid^10}"
device_format = "{ap}"
